### ISSUE TITLE
Company Job Page

### ISSUE THREAD

**Issue by carlobortolan** [Embloy/Embloy-Core-Client#20]
- Add a page that displays a list of jobs for a given company (e.g., `www.embloy.com/company/<company-id>`) 
- Relevant API endpoint to fetch the jobs: https://docs.embloy.com/#64569df3-92b1-4c45-8ee9-5f2f257b8938
- When applying for a job, the page should redirect to `https://apply.embloy.com/?eType=manual&mode=job&id=<company-id>&url=https://www.embloy.com/company/<company-id>/<job-slug>` 
    > E.g. `https://apply.embloy.com/?eType=manual&mode=job&id=8&url=https://www.embloy.com/company/8/lever__d067f0f0-5472-4a1b-a421-176473ebc3f4`

**Comment by github4touchdouble** [comment]
instead of react cicons in job lsit page
Use [lucide.dev](https://lucide.dev/) icons instead, just as you did in line 10 with:

import { AlignEndHorizontal, ArrowLeft, Bookmark, MapPin, Share2 } from "lucide-react";
(If some icons from [lucide.dev](https://lucide.dev/) are missing / not found in ts, you might need to wait for https://github.com/Embloy/Embloy-Core-Client/pull/22 to be merged first.)

**Comment by github4touchdouble** [comment]
add bookmark feature
